---

version: 2.1

jobs:
  ci:
    # ref: https://circleci.com/docs/2.0/executor-types/?section=executors-and-images#using-docker
    docker:
      # Use the base circle CI image
      - image: "cimg/python:3.7"
    steps:
      # TODO set up source and pip caching
      # checkout the git repo
      - checkout

      - run:
          name: "Check the value of $CIRCLE_TAG variable"
          command: |
            echo $CIRCLE_TAG

    environment:
      GROAPI_TOKEN: dummytoken

workflows:
  ci-workflows:
    jobs:
      - ci:
          filters:
            tags:
              only: /^v.*/

